name: Build Pango

on:
  push:
    branches: [ main, update-pango ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-win-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@v7
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch : x86
      - name: Build Pango x86
        run: |
          cd pango-build
          meson setup build-pango-x86 `
            --prefix=$env:GITHUB_WORKSPACE/prefix-pango-32
          meson compile -C build-pango-x86
          meson install -C build-pango-x86
      - uses: actions/upload-artifact@v7
        with:
          name: pango-build-x86
          path: prefix-pango-32/

  build-win-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@v7
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch : x64
      - name: Build Pango x64
        run: |
          cd pango-build
          meson setup build-pango-x64 `
            --prefix=$env:GITHUB_WORKSPACE/prefix-pango-64
          meson compile -C build-pango-x64
          meson install -C build-pango-x64
      - uses: actions/upload-artifact@v7
        with:
          name: pango-build-x64
          path: prefix-pango-64/

  # build-win-arm64:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v7
  #     - uses: actions/setup-python@v6
  #       with:
  #         python-version: '3.10'
  #         cache: 'pip'
  #     - name: Install deps
  #       run: pip install -r requirements.txt
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch : amd64_arm64
  #     - name: Build Pango arm64
  #       run: |
  #         cd pango-build
  #         meson setup build-pango-arm64 `
  #           -Dpixman:a64-neon=disabled `
  #           -Dpixman:iwmmxt=disabled `
  #           -Dpixman:mmx=disabled `
  #           --prefix=$env:GITHUB_WORKSPACE/prefix-pango-arm64 `
  #           --cross-file ../.ci/cross_amd64_arm64.txt
  #         meson compile -C build-pango-arm64
  #         meson install -C build-pango-arm64
  #     - uses: actions/upload-artifact@v7
  #       with:
  #         name: pango-build-arm64
  #         path: prefix-pango-arm64/

  build-mac-x64:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@v7
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Build Pango x64
        env:
          PKG_CONFIG: "invalid-exe"
          MACOSX_DEPLOYMENT_TARGET: "10.13"
        run: |
          cd pango-build
          meson setup build-pango-x64 \
            --prefix=$GITHUB_WORKSPACE/mac-prefix-pango-64
          meson compile -C build-pango-x64
          meson install -C build-pango-x64
      - uses: actions/upload-artifact@v7
        with:
          name: mac-pango-build-x64
          path: mac-prefix-pango-64/
  
  build-mac-arm64:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@v7
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Build Pango arm64
        env:
          PKG_CONFIG: "invalid-exe"
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        run: |
          cd pango-build
          meson setup build-pango-arm64 \
            --prefix=$GITHUB_WORKSPACE/mac-prefix-pango-arm64
          meson compile -C build-pango-arm64
          meson install -C build-pango-arm64
      - uses: actions/upload-artifact@v7
        with:
          name: mac-pango-build-arm64
          path: mac-prefix-pango-arm64/

  build-win-pkgconf:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@v7
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch : x64
      - name: Build pkgconf
        run: |
          cd pkgconf-build
          meson setup build-x64 `
            --prefix=$env:GITHUB_WORKSPACE/prefix-pkgconf
          meson compile -C build-x64
          meson install -C build-x64
      - uses: actions/upload-artifact@v7
        with:
          name: pkgconf-build
          path: prefix-pkgconf/


  release:
    permissions:
      contents: write
    runs-on: windows-latest
    needs: [build-win-x86, build-win-x64, build-win-pkgconf, build-mac-x64, build-mac-arm64]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: pango-build-x86
          path: pango-x86/
      - uses: actions/download-artifact@v8
        with:
          name: pango-build-x64
          path: pango-x64/
      # - uses: actions/download-artifact@v8
      #   with:
      #     name: pango-build-arm64
      #     path: pango-arm64/
      - uses: actions/download-artifact@v8
        with:
          name: mac-pango-build-x64
          path: mac-pango-x64/
      - uses: actions/download-artifact@v8
        with:
          name: mac-pango-build-arm64
          path: mac-pango-arm64/
      - uses: actions/download-artifact@v8
        with:
          name: pkgconf-build
          path: pkgconf/

      - name: Zip it
        shell: bash
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          7z a "pango-$RELEASE_TAG-windows-x86.zip" pango-x86/*
          7z a "pango-$RELEASE_TAG-windows-x64.zip" pango-x64/*
          # 7z a "pango-$RELEASE_TAG-arm64.zip" pango-arm64/*
          7z a "pkgconf-$RELEASE_TAG-windows.zip" pkgconf/
          7z a "pango-$RELEASE_TAG-mac-x64.zip" mac-pango-x64/*
          7z a "pango-$RELEASE_TAG-mac-arm64.zip" mac-pango-arm64/*

      - name: Upload release assets
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          gh release upload "$RELEASE_TAG" \
            "pango-$RELEASE_TAG-windows-x86.zip" \
            "pango-$RELEASE_TAG-windows-x64.zip" \
            "pkgconf-$RELEASE_TAG-windows.zip" \
            "pango-$RELEASE_TAG-mac-x64.zip" \
            "pango-$RELEASE_TAG-mac-arm64.zip"
